apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription
spec:
  selector:
    matchLabels:
      app: subscription
  replicas: 1
  template:
    metadata:
      labels:
        app: subscription
    spec:
      containers:
      - name: subscription
        image: svizor/zoomcamp-model:3.11.5-hw10
        resources:    
          limits:
            memory: "256Mi"
            cpu: "0.5"
        ports:
        - containerPort: 9696